# Generated by Django 6.0.7 on 2026-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("application_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "matching_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("cv", models.CharField(blank=True, max_length=255, null=True)),
                ("cover_letter", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "applications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Companies",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=150)),
                ("email", models.CharField(blank=True, max_length=150, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "companies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("experience_required", models.IntegerField(blank=True, null=True)),
                (
                    "education_required",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vacancies", models.IntegerField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=8, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JobSkills",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "job_id",
                        "skill_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("required", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_skills",
                "managed": False,
            },
        ),
    ]
