# Generated by Django 6.0.7 on 2026-07-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applications",
            options={
                "managed": False,
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="categories",
            options={
                "managed": False,
                "verbose_name": "Categorie",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="companies",
            options={
                "managed": False,
                "verbose_name": "Compagnie",
                "verbose_name_plural": "Compagnies",
            },
        ),
        migrations.AlterModelOptions(
            name="jobs",
            options={
                "managed": False,
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
    ]
