# Generated by Django 6.0.7 on 2026-07-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_applications_options_alter_categories_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applications",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="categories",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="companies",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="jobs",
            options={"managed": False},
        ),
    ]
