# Generated by Django 6.0.7 on 2026-07-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_applications_options_alter_categories_options_and_more"),
        ("jobs", "0003_enable_management_and_defaults"),
    ]

    operations = []
