# Generated by Django 6.0.7 on 2026-07-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_restore_relationship_state"),
    ]

    # La colonne est déjà un ENUM MySQL : seule la validation Django évolue.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="applications",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("UNDER_REVIEW", "En cours d'examen"),
                            ("INTERVIEW", "Entretien"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Refusée"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
