# Generated by Django 6.0.7 on 2026-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_applications_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="cv",
            field=models.FileField(
                blank=True, max_length=255, null=True, upload_to="applications/cv/"
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="logo",
            field=models.FileField(
                blank=True, max_length=255, null=True, upload_to="companies/logos/"
            ),
        ),
    ]
