# Generated by Django 6.0.7 on 2026-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("is_read", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "notifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profiles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=6, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("education", models.CharField(blank=True, max_length=150, null=True)),
                ("experience_years", models.IntegerField(blank=True, null=True)),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "profiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileSkills",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "profile_id",
                        "skill_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                "db_table": "profile_skills",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "skills",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("role", models.CharField(max_length=10)),
                ("is_active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
