# Generated by Django 6.0.7 on 2026-07-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifications",
            options={
                "managed": False,
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="profiles",
            options={
                "managed": False,
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="skills",
            options={
                "managed": False,
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AlterModelOptions(
            name="users",
            options={
                "managed": False,
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
