# Generated by Django 6.0.7 on 2026-07-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_notifications_options_alter_profiles_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifications",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="profiles",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="skills",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"managed": False},
        ),
    ]
