# Generated by Django 6.0.7 on 2026-07-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_notifications_options_alter_profiles_options_and_more",
        ),
        ("accounts", "0003_enable_management"),
    ]

    operations = []
