# Generated by Django 6.0.7 on 2026-07-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_restore_relationship_state"),
    ]

    # Les tables et leurs ENUM existent déjà dans MySQL. Cette migration
    # aligne uniquement l'état Django, sans remplacer les ENUM par VARCHAR.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="profiles",
                    name="gender",
                    field=models.CharField(
                        blank=True,
                        choices=[("MALE", "Homme"), ("FEMALE", "Femme"), ("OTHER", "Autre")],
                        max_length=6,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="users",
                    name="role",
                    field=models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("RECRUITER", "Recruteur"),
                            ("JOB_SEEKER", "Candidat"),
                        ],
                        default="JOB_SEEKER",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
