# Generated by Django 6.0.7 on 2026-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profiles_gender_alter_users_role"),
    ]

    # La colonne varchar(255) existante stocke déjà le chemin du fichier.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="profiles",
                    name="photo",
                    field=models.FileField(
                        blank=True, max_length=255, null=True, upload_to="profiles/"
                    ),
                ),
            ],
        ),
    ]
